resources_info_plural = [
        {'id' : "farmers-markets",      
                'name' : "Farmers' Markets",  
                'lowercase_name' : "farmers' markets",
                'enum' : 'FARMERS_MARKET', 
                'underscore_id' : 'farmers_markets'}, 
        {'id' : "food-cupboards",       
                'name' : "Food Cupboards", 
                'lowercase_name' : "food cupboards",
                'enum' : 'FOOD_CUPBOARD', 
                'underscore_id' : 'food_cupboards'},
        {'id' : "senior-meals",      
                'name' : "Senior Meals", 
                'lowercase_name' : "senior meals",
                'enum' : 'SENIOR_MEALS', 
                'underscore_id' : 'senior_meals'},
        {'id' : "share-host-sites",     
                'name' : "SHARE Host Sites", 
                'lowercase_name' : "SHARE host sites",
                'enum' : 'SHARE', 
                'underscore_id' : 'share_host_sites'},
        {'id' : "soup-kitchens",        
                'name' : "Soup Kitchens", 
                'lowercase_name' : "soup kitchens",
                'enum' : 'SOUP_KITCHEN', 
                'underscore_id' : 'soup_kitchens'},
        {'id' : "wic-offices",          
                'name' : "WIC Offices", 
                'lowercase_name' : "WIC offices",
                'enum' : 'WIC_OFFICE', 
                'underscore_id' : 'wic_offices'}]

resources_info_singular = [
        {'id' : "farmers-market",          
                'name' : "Farmers' Market", 
                'lowercase_name' : "farmers' market",
                'enum' : 'FARMERS_MARKET', 
                'underscore_id' : 'farmers_market'}, 
        {'id' : "food-cupboard",        
                'name' : "Food Cupboard",
                'lowercase_name' : "food cupboard",
                'enum' : 'FOOD_CUPBOARD', 
                'underscore_id' : 'food_cupboard'},
        {'id' : "senior-meal",       
                'name' : "Senior Meal",
                'lowercase_name' : "senior meal", 
                'enum' : 'SENIOR_MEAL', 
                'underscore_id' : 'senior_meal'},
        {'id' : "share-host-site",              
                'name' : "SHARE Host Site", 
                'lowercase_name' : "SHARE host site",
                'enum' : 'SHARE', 
                'underscore_id' : 'share_host_site'},
        {'id' : "soup-kitchen",         
                'name' : "Soup Kitchen", 
                'lowercase_name' : "soup kitchen",
                'enum' : 'SOUP_KITCHEN', 
                'underscore_id' : 'soup_kitchen'},
        {'id' : "wic-office",           
                'name' : "WIC Office", 
                'lowercase_name' : "WIC office",
                'enum' : 'WIC_OFFICE', 
                'underscore_id' : 'wic_office'}]

days_of_week = [
	{'id' : "sunday",      
                'name': "Sunday",       
                'index' : 0},
	{'id' : "monday",      
                'name': "Monday",       
                'index' : 1},
	{'id' : "tuesday",     
                'name': "Tuesday",      
                'index' : 2},
	{'id' : "wednesday",   
                'name': "Wednesday",    
                'index' : 3},
	{'id' : "thursday",    
                'name': "Thursday",     
                'index' : 4},
	{'id' : "friday",      
                'name': "Friday",       
                'index' : 5},
	{'id' : "saturday",    
                'name': "Saturday",     
                'index' : 6}]
