resources_info_plural = [
        {'id' : "farmers-markets",      
                'name' : "Farmers' Markets",  
                'lowercase_name' : "farmers' markets",
                'enum' : 'FARMERS_MARKET'}, 
        {'id' : "food-cupboards",       
                'name' : "Food Cupboards", 
                'lowercase_name' : "food cupboards",
                'enum' : 'FOOD_CUPBOARD'},
        {'id' : "meals-on-wheels",      
                'name' : "Meals On Wheels", 
                'lowercase_name' : "Meals On Wheels",
                'enum' : 'MEALS_ON_WHEELS'},
        {'id' : "share-host-sites",     
                'name' : "SHARE Host Sites", 
                'lowercase_name' : "SHARE host sites",
                'enum' : 'SHARE'},
        {'id' : "soup-kitchens",        
                'name' : "Soup Kitchens", 
                'lowercase_name' : "soup kitchens",
                'enum' : 'SOUP_KITCHEN'},
        {'id' : "wic-offices",          
                'name' : "WIC Offices", 
                'lowercase_name' : "WIC offices",
                'enum' : 'WIC_OFFICE'}]

resources_info_singular = [
        {'id' : "farmers-market",          
                'name' : "Farmers' Market", 
                'lowercase_name' : "farmers' market",
                'enum' : 'FARMERS_MARKET'}, 
        {'id' : "food-cupboard",        
                'name' : "Food Cupboard",
                'lowercase_name' : "food cupboard",
                'enum' : 'FOOD_CUPBOARD'},
        {'id' : "meals-on-wheel",       
                'name' : "Meals On Wheels",
                'lowercase_name' : "Meals On Wheels", 
                'enum' : 'MEALS_ON_WHEELS'},
        {'id' : "share-host-site",              
                'name' : "SHARE Host Site", 
                'lowercase_name' : "SHARE host site",
                'enum' : 'SHARE'},
        {'id' : "soup-kitchen",         
                'name' : "Soup Kitchen", 
                'lowercase_name' : "soup kitchen",
                'enum' : 'SOUP_KITCHEN'},
        {'id' : "wic-office",           
                'name' : "WIC Office", 
                'lowercase_name' : "WIC office",
                'enum' : 'WIC_OFFICE'}]

days_of_week = [
	{'id' : "sunday",      
                'name': "Sunday",       
                'index' : 0},
	{'id' : "monday",      
                'name': "Monday",       
                'index' : 1},
	{'id' : "tuesday",     
                'name': "Tuesday",      
                'index' : 2},
	{'id' : "wednesday",   
                'name': "Wednesday",    
                'index' : 3},
	{'id' : "thursday",    
                'name': "Thursday",     
                'index' : 4},
	{'id' : "friday",      
                'name': "Friday",       
                'index' : 5},
	{'id' : "saturday",    
                'name': "Saturday",     
                'index' : 6}]
